const myExercises = [
  {
    name: 'Descanso',
    videoLink: '',
    gif: '',
    time: 0,
    howMuch: {
      principiante: 60,
      amador: 50,
      intermediario: 40,
      avancado: 30,
      profissional: 30,
    },
  },
  {
    name: 'Abdominal Reto',
    videoLink: 'tFKEaPlD9BI?t=18',
    gif: 'abdominal-reto.gif',
    time: 120,
    howMuch: {
      principiante: 10,
      amador: 20,
      intermediario: 30,
      avancado: 40,
      profissional: 50,
    },
  },
  {
    name: 'Prancha Lateral',
    videoLink: '',
    gif: 'prancha-lateral.gif',
    time: 120,
    howMuch: {
      principiante: 10,
      amador: 15,
      intermediario: 20,
      avancado: 30,
      profissional: 40,
    },
  },
  {
    name: 'Prancha',
    videoLink: 'aom6LgVsQL8?t=33',
    gif: 'prancha.gif',
    time: 0,
    howMuch: {
      principiante: 30,
      amador: 45,
      intermediario: 60,
      avancado: 100,
      profissional: 120,
    },
  },
  {
    name: 'Agachamento',
    videoLink: '',
    gif: 'agachamento.gif',
    time: 120,
    howMuch: {
      principiante: 10,
      amador: 15,
      intermediario: 20,
      avancado: 30,
      profissional: 40,
    },
  },
  {
    name: 'Flexão',
    videoLink: 'dzHLpuRMucs?t=238',
    gif: 'flexao.gif',
    time: 120,
    howMuch: {
      principiante: 5,
      amador: 10,
      intermediario: 20,
      avancado: 30,
      profissional: 40,
    },
  },
  {
    name: 'Bench Dip',
    videoLink: '',
    gif: 'bench-dip.gif',
    time: 120,
    howMuch: {
      principiante: 5,
      amador: 10,
      intermediario: 20,
      avancado: 30,
      profissional: 40,
    },
  },
];

export default myExercises;
